name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome New Member! Thank you for contributing to this project and we hope to see many more commits from you!'' first issue'
        pr-message: 'May the force be with this Pull Request'' first pr'
